[project]
name = "novelcrawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiofiles>=24.1.0",
    "playwright>=1.54.0",
    "pydantic>=2.11.7",
]
